services:
  - type: web
    name: gem-bid-verification-backend
    env: python
    buildCommand: "cd gem-backend && pip install -r requirements.txt"
    startCommand: "cd gem-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
